

# A beginner's guide to broadcasting in Numpy


### What is Numpy?

NumPy is one of the most powerful Python libraries. It is used in the industry for array computing. This notebook will  provide an overview of the common mathematical functions in an easy-to-follow manner.
Numpy is gaining popularity and is being used in a number of production systems. Hence, it’s important to understand what this library offers.

- np.zeroes
- np.delete
- np.arange
- np.split
- np.delete

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [35]:
!pip install jovian --upgrade -q

In [36]:
import jovian

In [37]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pranavrnambiar/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pranavrnambiar/numpy-array-operations


'https://jovian.ml/pranavrnambiar/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [38]:
import numpy as np

In [39]:
# List of functions explained 
function1 = 'np.zeros' 
function2 = 'np.full'
function3 = 'np.arange'
function4 = 'np.split'
function5 = 'np.delete'

## Function 1 - np.zeros 

The normal syntax for this function is numpy.zeros(shape, dtype=float, order='C') where the shape allows us to define the size of the matrix , dtype allows to define the datatype and order allows users to  define to store multi-dimensional data in coloumn major or row major style

In [40]:
# Example 1 - working (change this)
arr1=np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

The np.zeros functions allows the user to make  a zero matrix, in this example since we dint mention the data type it is taken as float and the size is restricted to (5,1)

In [41]:
# Example 2 - working
arr2=np.zeros((3,3),dtype=int)
arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Here we gave the dtype as int and this results in the array having zeros with no decimal points and we defined the size to 3,3 

In [42]:

np.zeros(4,4, dtype=int)

TypeError: Cannot interpret '4' as a data type

The common mistake we do is to forget the brackets seperating the shape and dtype which results in  this error,
the right way to do is 
np.zeros((4,4),dtype=int)

The function is used when we need a matrix of with all its elements as zero, to test a certain operation etc. 

In [ ]:
jovian.commit()

## Function 2 - np.full

np.full is used when the we want a matrix with all its elements as the same digits, The syntax is numpy.full(shape, fill_value, dtype=None, order='C')
where the fill_value determines what number should be filled in the matrix.

In [ ]:
# Example 1 - working
np.full((2, 2), 10)



Here  first we determine the size of the matrix and  then we determine the number/fill value. 

In [ ]:
# Example 2 - working
np.full((2, 2), [4, 6])

In this example after determining the size of the matrix we then go onto plug in an array as the fill value

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.full((3, 4), [1, 2])

The error here is that the size of the fill value array does not match with the shape of the array we defined. So this shows that the size should always match between the fill value  array and the shape of numpy array 

We use  this function when we need an iddentity matrix to test the output of a certain complex function

In [ ]:
jovian.commit()

## Function 3 - np.arrange

numpy.arange([start, ]stop, [step, ]dtype=None)
Return evenly spaced values within a given interval.

Results  are generated within the half-open interval [start, stop)  For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

In [ ]:
# Example 1 - working
np.arange(3)

The default is 0 for start , the stop value has to be mentioned which 3 , so the output comes till 3 with 3 excluded

In [ ]:
# Example 2 - working
np.arange(3,7)

Here we mention the start value as 3 and the end value as 7 hence till 6 the end value is included

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange()


Not specifying the end value can lead to an error , the jump value and the initial value is optional and depends on the use case

Here the resultant will be an array in which we can specify the start, end value , the jump value etc.

In [ ]:
jovian.commit()

## Function 4 - np.split

numpy.split(ary, indices_or_sections, axis=0), This function splits an array into subarrays.

ary- refers to the array which has to be split,
indices- refers where or which index it has to be split, 
axis -refers to the  axis it has to be split , the default is 0 

In [43]:
# Example 1 - working
x = np.arange(6.0)
np.split(x, 3)

[array([0., 1.]), array([2., 3.]), array([4., 5.])]

Here the array is broken as equal divisions of 3 

In [44]:
# Example 2 - working
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Here the split happens at the specified index i.e 3,5,6 and 10

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.arange(8.0)
np.split(x, 3)

ValueError: array split does not result in an equal division

Here the numbers from 0 to 8 cannot be split in 3 ways , so we have to change the split value to 4  

This function is usefull when we have to make subarrays with just the index in mind or with the number subarrays in mind 

In [46]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pranavrnambiar/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/pranavrnambiar/numpy-array-operations


'https://jovian.ml/pranavrnambiar/numpy-array-operations'

## Function 5 - np.delete

This function is used when we have to delete an axis from our array. The syntax is np.delete(arr, obj, axis=None)

In [47]:
# Example 1 - working
arr = np.array([[1,2,3,4], [5,3,4,2], [19,30,44,53]])
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [19, 30, 44, 53]])

Here the entire 1st row is deleted 

In [48]:
# Example 2 - working
np.delete(arr, [1,3,5], None)

array([ 1,  3,  5,  4,  2, 19, 30, 44, 53])

Because of the axis as none it flattents the array 
hence resulting in an 1d array with all the  elements from the position 1,3 and 5 deleted


In [49]:
# Example 3 - breaking (to illustrate when it breaks)
np.delete(arr, 1,3,5 )

TypeError: _delete_dispatcher() takes from 2 to 3 positional arguments but 4 were given

The index that should be deleted must be specified in a [ ]  bracket

The function is highly useful when  a row has some descrepancies and you have  to delete it 

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

We have covered almost all the usefull numpy operations which are used heavily in broadcasting. With  the rapid expansion of Data Science numpy has still remained  the golden standard and the most used library in python for Calculations.

Hope you guys enjoyed my notebook



Adios

## Reference Links

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html


In [ ]:
jovian.commit()